jasypt:
  encryptor:
    password: hello
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES

spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/sportsgeekdb
#    username: root
#    password: ENC(QRWFXH2r6PfEQmr/WPB1Gw==)
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:mysql://sportsgeekdb.czwuknrdjddo.ap-south-1.rds.amazonaws.com:3306/sportsgeekdb
    username: ENC(BglRPvY2GycD4N4wo7KE6w==)
    password: ENC(Z54EdNXG1dKMtnP4y/0ukPet3Ogg9BRj)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: info.sportgeek@gmail.com
    password: ENC(jtgUkGZLn5sHz8UgrZxft2wp4IyKQxouPRVN07zxP5w=)
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          starttls:
            enable: true

server:
  port: 8080