@startuml
skinparam ParticipantPadding 10
skinparam BoxPadding 20
actor User
box "Forget Password Service"
 participant forgetPassword
end box
box "database"
    participant database
end box
box "email service"
    participant email
end box
User -> forgetPassword: POST /forget-password
alt #white
note right #yellow
    *params*
    email=xyz123@gmail.com
    mobileNumber=9632587410
    end note
activate "forgetPassword" #lightblue
    forgetPassword -> "database" : Check Email and Mobile number
    activate "database" #lightblue
    "database" -> "forgetPassword" : <font color=darkblue><b>return "Response Email and Mobile Number Match"
    deactivate "database"
alt #lightgreen If Email and Mobile Number Match
"forgetPassword" -> email : <font color=darkblue><b>"Mail Sent to User"
"forgetPassword" -> User : <font color=darkblue><b>return "Response 200 OK"
else #pink Email and Mobile Number Not Match
"forgetPassword" -> User : <font color=darkblue><b>return "Response 404 Email Id or Mobile Number Not Found"
end alt
deactivate "forgetPassword"
User -> forgetPassword: PUT /forget-password
activate "forgetPassword" #lightblue
note right #yellow
    *params*
    otp=123456
    password=******
    userId=1
    end note
    "forgetPassword" -> "forgetPassword" : Verify OTP
     forgetPassword -> "database" : Update Password of User
     activate "database" #lightblue
     "database" -> "forgetPassword" : <font color=darkblue><b>return "Response 200 OK Password Updated"
     deactivate "database"
alt #lightgreen If OTP Match
    "forgetPassword" -> User : <font color=darkblue><b>return "Response 200 OK Password Updated Successfully"
else #pink If Not Match
"forgetPassword" -> User : <font color=darkblue><b>return "Response 404 OTP Not Match"
end alt
else #pink Internal Server Error
"forgetPassword" -> User : <font color=darkblue><b>return "Response 500 INTERNAL SERVER ERROR
end alt
deactivate "forgetPassword"
@enduml