@startuml
skinparam ParticipantPadding 10
skinparam BoxPadding 20
actor User
box "User Service"
 participant user
end box
box "database"
    participant database
end box
box "email service"
    participant email
end box
User -> user: POST /register
alt #white
note right #yellow
    *params*
    firstName=xyz
    lastName=pqr
    genderId=1
    username=xyz112
    password=******
    email=xyz123@gmail.com
    mobileNumber=9632587410
    availablePoints=500
    profilePicture=xyz.png
    end note
activate user #lightblue
    user -> "database" : Check user exists
    activate "database" #lightblue
    "database" -> "user" : <font color=darkblue><b>return "Response not exist user"
    user -> "database" : add user details
     "database" -> email : <font color=darkblue><b>"Mail Sent to User"
        "database" -> user : <font color=darkblue><b>return "Response user added"

deactivate "database"
alt #lightgreen If user added
"user" -> User : <font color=darkblue><b>return "Response 201 Created"
else #pink UserName Already Exist
"database" -> "user" : <font color=darkblue><b>return "User exist"
"user" -> User : <font color=darkblue><b>return "Response 404 "Username already exist"
else #pink Email Already Exist
"database" -> "user" : <font color=darkblue><b>return "Email exist"
"user" -> User : <font color=darkblue><b>return "Response 400 "Email already exist"
end alt
else #pink Internal Server Error
"database" -> "user" : <font color=darkblue><b>return "Failed to add User"
"user" -> User : <font color=darkblue><b>return "Response 500 INTERNAL SERVER ERROR

end alt
@enduml