@startuml
header SportsGeek
title Forget Password
skinparam ParticipantPadding 10
skinparam BoxPadding 20
actor User
box "SportsGeek System"
 participant sportsGeek
end box
box "Forget Password Service"
 participant forgetPassword
end box
box "database"
    database database
end box
box "email service"
    participant email
end box
User -> sportsGeek: Enter the mobile no and email id
activate sportsGeek #lightblue
alt #white
note right #yellow
    *params*
    email=xyz123@gmail.com
    mobileNumber=9632587410
    end note
    sportsGeek -> "forgetPassword" : Check Email and Mobile number
activate "forgetPassword" #lightblue
    forgetPassword -> "database" : Check Email and Mobile number
    activate "database" #lightblue
alt #lightgreen If Email and Mobile Number Match
"database" --> "forgetPassword" : <font color=darkblue><b>Response Email and Mobile Number Match
"forgetPassword" -> email : <font color=darkblue><b>Mail Sent to User
"forgetPassword" --> "sportsGeek" : <font color=darkblue><b>Response Email and Mobile number Match
"sportsGeek" --> User : <font color=darkblue><b>Response Email and Mobile number Match
else #pink Email and Mobile Number Not Match
"database" --> "forgetPassword" : <font color=darkblue><b>Response Email Id or Mobile Number Not Found
deactivate "database"
"forgetPassword" --> "sportsGeek" : <font color=darkblue><b>Response Email Id or Mobile Number Not Found
deactivate "forgetPassword"
"sportsGeek" --> User : <font color=darkblue><b>Response Email Id or Mobile Number Not Found
deactivate "sportsGeek"
end alt


User -> "sportsGeek": update password
activate sportsGeek #lightblue
note right #yellow
    *params*
    otp=123456
    password=******
    userId=1
    end note
    "sportsGeek" -> "forgetPassword" : Verify OTP
    activate "forgetPassword" #lightblue
    "forgetPassword" --> "forgetPassword" : Verify OTP
     forgetPassword -> "database" : Update Password of User
     activate "database" #lightblue
     "database" --> "forgetPassword" : <font color=darkblue><b>Response Password Updated
     deactivate "database"
alt #lightgreen If OTP Match
"forgetPassword" --> "sportsGeek" : <font color=darkblue><b>Response Password Updated Successfully
    "sportsGeek" --> User : <font color=darkblue><b>Response Password Updated Successfully
else #pink If Not Match
"forgetPassword" --> "sportsGeek" : <font color=darkblue><b>Response OTP Not Match
deactivate "forgetPassword"
"sportsGeek" --> User : <font color=darkblue><b>Response OTP Not Match
deactivate "sportsGeek"
end alt
end alt
@enduml